"""GENERATED by tools/recolor.py - do not edit by hand.

Pixel classes (high nibble) / shade (low nibble, 0 dark .. 3 light).
FRAMES: frame_id -> (w, h, anchor_x, anchor_y, data); data = w*h bytes, row major,
each byte (class << 4) | shade. anchor = bottom-centre (feet).
"""
import base64 as _b64
import zlib as _zlib

CLASSES = {0: 'transparent', 1: 'outline', 2: 'hair', 3: 'skin', 4: 'shirt', 5: 'pants', 6: 'gun', 7: 'shoe', 8: 'white', 9: 'fx'}

_BLOB = _zlib.decompress(_b64.b64decode(
    'eNq1fYvZpSrSriGMGbSSgLgSaDUCIYH5XInM7pP4gbpRICr2zO+zn+7ey7cQUal7VdcVh4Gjuz/MmI5b7Dg2If2YH/4KdwJe'
    'jOldjnO+bbxLYBrPzvN8czMMtJ94zJc4WUICWvO8hibirL0H2vhHmGMA3lzbmnAfJuICcJ6vh4y3O+MU52vcujpHuHm+AW4R'
    '6KaZYZe4AFy9myaCzZ8r3AbQlZB27G6AEbpMcEdXD3pdGRjmOcYn7byv4hi4uD0+8yHgfe1+1y0Bl2Xfd1cbcdXAnYHnEcPZ'
    'ZYH5ReCyu4Bb1jMQFmVZ+VhgwDXeVZdf/QwMB9x9Mc9tzQ8CnpFr5QjQgCpuSY+4wO1HYBxuH8bsljYAwOWWxcMiuWGapiEc'
    '+cU3mJaDP8IJ74cBHncAjvl6RmSYUcA6XGt80cYTsAMAQPAveM/jHoC3rr79nYE45ISvpMcbz5AOfuEh4yRhOHrqvg4Mfw54'
    'y/R/alBPz0GdCn+vcQSXIxHnaVZ4W05GUJf3DIwgBssQepoEBCRfnndY32W3cwbKHWT7rQDdCVjDxWu4ck30tqyAfr8G+j0h'
    'w+jXOF4CH0/K0nX1K8so7hKIQ/B7QgPulSsDApBeRt/32i2Hu4QF1Li9cmF4BX2Hk3Kn90UD1alrYCe4/J5PG59XQJcW8Txo'
    'dqoAumtg/r/+Rp4xyI6NmRulnmtWKPwaGHFgrleXxCvCpmPGS7Zu5IIG5I4LycNkgtY1bhz0PdwMNwxKPAmb2IUsEXYkkopI'
    'RuiucYMa7wrnGQd3fLN8NJrB27hevnAfKEDcL3O3LBNKOoC19nMlvyxLfGqIu7zfDThVuPTnE96pz5X8Etl4RMZLG3MtD6Fw'
    'sNIc5wupEqUCvPQ0oph6KwtFpkrvqbnEJRZ9scHhVRUzv8CtPDuaIrB6fzEcyEMsjtQFIcGJMILffFWwSjgWWfI5riyA6QEr'
    'O4zgFHBn0caVQlBa6fUfWL9hB+49lsKS4P755x94+ePb7eKGVApVdOGAM/wFZ89PSXPxFrb/RBiKK3CkK5OoR0s8wMv6+YCk'
    'lAHDJrrwEbh2kFUiTHBHyelo4QTHVz5qmzRcmW8jEsW/zqwz4hxvSVFQAhy/FS6XfVBCCqqhiUsNOJ9wwBIBtw/MFuJPAPOl'
    '4CMCHT5cT6dKAckpnGe5J72KHsTuyGKTdFblRyx6XDK4injkSCI4D+hdwvlObt7XRRTE3cgo3iWgV0/xWuTxXUX+rDBrTeSv'
    'JSPf3YlajkV0LcxWBKNMQvWXl3V7JsnK/17j6G53t1cmqKQn528Ek0x+90n8L4E1kcjXB1T0+Mb4a2m1PP40QJ4x/wlH12Yn'
    'Oo5nQ9JxHN8z5DgKW84ZNJaQ01BmrBxHNimjZaiLiZthqIK+xS2JqENHFGlyqSQJayjDhGOyXR1jSSYBM9EFJkqcOE4pWy0a'
    'hOPZaerOmOLOaphw9yTghkEAk11rxWuBCQqnVHIn5P1w3x8Ujj4MKoSsZRzF7vRBKU+4Idt8Ake0yjilMZuWcibQ7MPVDGCI'
    '+25bkqziBWlGBv5QVyIjBk7d0pWsYuEgwoXJMIZAajKCWVa+WlxJWEsjGrWwMFYTYblNWhxhDbwzxd1HHolRmBy3u1yeUBi1'
    'f8F5S6+P5gmKH1m0QCYMGTY0BDUBxLgKJtwf2Uan6VPsZGkYUjwsiuwZhrbP3ZFlktQ7JxYV5wNZ+Hsc96gmwPthO2H0uMpw'
    'Ky59Yvq7YQnBoqWHxJMwpivU3B0vwCPVNNfw64CWWxZbKmzJePym1E36ur4Ft951/kbtTQade0zXcqDjYFQya3HE9YlbB+6M'
    'FU3nY2lL5M3TXKu5CIl/5APNaV9KO/ChN8N5GmuY8YEHFJDa9j5kMza5Pm5nuv8qs+HdAt6h7hKCG1ihjAvEREs+vsP52uU3'
    'ZGbaSa8ZLDOAW8h4hgTWGDcsS7uamrna+X/HPdvOuKEbnK18d7BPoq5BmzEti1EQVg+X3+IfCK+eTQ4F0TTjWOTBiN6Oj0BW'
    'UjBJUaL1H+mSZzs2b9bMkD6ZARu0yhXmPDM715u+aJ7h7ofEzrP93ImsF/cKgmRbftzF+96pndqKYYEGQchOQh5bZk7XIZHV'
    'kyI1WqsgYsBmQTR6TAILtyh1Boiyhu9sO4dtOu6MNNFdDRNnROwXBIGkW7Ehug+QiSCwvyatihQYGIReCfrofbKLy4hidB+7'
    'DJJxFpJKjJKkSwh+30YL0bsrIZHtVkVyXAAEmc+FfsS8ubpf8u1c7e9pnMf927Vu3rB33/p+Tb5rmkccb9IXoxraafRuaq7G'
    'M3c7D1s38315uACaIQfC/4U/qgOeRgy/nIA5zsbdyI7D/ZWtkvqvgEPCwRZ2BcRRldBpqsC01MxtjL0AwtuQ/iwUk5qWY0gz'
    '6i6W0Vp8ycL0kPBsIlwIGJ3XYeOaaURTdYOG7TZKj+iOM8RlPycTJmzN02Rn2tzjp49O4E/h9UXLafJOW1QEkgNaW+ACH8uX'
    'W7m0tyrvSII+73KdkvcJOsKbw2sDuE+mGDBy0FuUcJyz9cjRq/FhoOIp7CFiZHzfULpNLJt5gtIUSO+LM8txHvdi2VBRPbSk'
    'DMy8SxKT8cQndmB4vG/LxpyGUUCR07WWUgVOpPEpoSsxP2Xc2618hbKdZ1xStAUrIpp8XT4HsmvTnkU5n5iMMt5NqAKX9q7s'
    'wknpKr4D790JFoCDc+ba1KaO/collr9BdxyI7VWdv0eJfa5Fk/BtPEs50uL3d8+5cmn/PihH7Wrm0RF4zYzqeoQZz7vos2B9'
    '3pVxYxxucJoHDqc7yZkuKA+mxtk0Tva7INXc4ShgKH57N57F5DS0VdyYuVvxe7JPi2yBYxTmporyYnG+aErTbrewsS46jsqO'
    'yY2rcLQX85p84DMmbqRwElFD7AflW8TNCZeik1Dr+bCFzuZhUmsBRMsYw7qkdKwJxy5mtth8PnwjOZNaERh34JlMv/9Bm6by'
    'nMEBy6JUzD9o+8yiguIRX8RJfUTE/pih7IpD6W/N+2R82lP0SzI9pcgSzZ+cDhVJH68n5493zMfUjk1vfrhtz6YWGUaxkn2g'
    'NzDaXXwmwmc8Z2DmZKfMNbWTjpJwJLRYV8e5xOvwRTjjdrJvgR+LcPGy/syYYIUQS4xJBd3IpDIb3mgxyNGXcSKkNxKOvuV8'
    '51XanxjqoktuNN11RIlazwuWlBkq3YNZ61F1EmATp3nFkNgU9hhF+zaYNgscEVZmmuDaav9tdMWIcnS040kVub3bnD0NF7rA'
    '1XwGorghyC5gKajvep1yTshhgDf3cAiLtRIce3cL3XEMY0EQNtCbRwe+LLyKbN/0dtTJiEBuIelNpTFQCI4sEoguFl8YW42i'
    'PdJNxDlZCsAJDBc0lkCZ617fA/1JHECMy2rBHWTBSpbFHaeIilm5upiAmfBcCegVNcxQKFX26E1SGTm8dllE7WZTKG530UCY'
    'u3RIe1xZfwu3KgDLgRWmiEWGA3daY5UqDpEYsxDwbJhisnPOV1PkhnIOreA/QnUwqlZaUgz/1G9iZpwk/THbZUBkUW/upqJx'
    'yaS5agIjclGuXa9aM1Ub2febi7K8QoUqK3FwX3onjY4YohtOBBIFNR/x0C+3EEjsEDrcyLI4Dkfu701qtYo2AnWdPuqh9A/z'
    'G0RPYVGmatoFvt9zJDtdgS0HcUbzleSrHlqK04I3EPGmu6bInJnWzlXJmmO+l0RBA0zWXrGgQgRkY8UNy6oFga/j3TYZJpKZ'
    'TsLVWvinotgaGTSA33D07jVBJgm0gR/UyStHWIvcUDq8TKM88iyYXDjLTKt0AWzk52gZnKzJQ9V5WBVF6hpystkWsbDXIZPF'
    '6Ik/mYa0ndHMHJ1ws4xD5qHDyVyPfo4vsXdPKaH5XyxDfSvS4LYMuQBFcNMd+KTyIB3YGMjFiQbTqJTGpzr+/KDkcOgvCbZM'
    'CDfkdYx7889PfBG+CD/yjxsUaIpsMfAnwH9+jpjClOCZeoxmYQzlMEdcmoNEF6PjVmn/m3BwAw7+9PbBK6HiTYUA1W+wU38k'
    'tBrZe7EpRTLiWUroo7eINugtZxPxfrPviISZIJiZxHiFDS0FY5cMsFIwET/lWsD1my8Wbk64QTSL3PhK2DxkRQkBC4sAsJLT'
    'hP/ULD1NA/FiWQroyerdIAXtbpuCQ+TInz9zgE8qrnTTcBl+wgS7/wdwnROnIng5SAj47OfDUSd5OLaGb8IAxdZVxm5ncHq8'
    'Yhs7R3qr1U6mG7KRzZUweFhFfgNoQqMY5msc7ARnvL3hqkvmKDfmco8B5t3p5LC1jXeTkNbGu/Hdaee/W7tMQHfxmsWz0Oof'
    'kT4GCTaxd5/lrx7fW2P5dRTiCZqMBjcDz+FRejaOJbfrcfX4ElSOvv7kcN9P/Nba+lLI7pAZnauyLL9uv9GrD6kW8YPx1wkD'
    'C1n+TDKa1TMaNspGBBUUrLbTOSCL2QJBUYELazado7c2gQIY9EMQ0c9Ru5tkfGAyJpiM464BZrBA7s8JE6QfLRIFFI2asKll'
    '01XQldlqwEcD6Jp/Lko5AvDIATRhCjjOlus5SUFACyJCHcUyll/9otJKHNv3lpMkDxFD6HD9XZgLUUlSQ2+89/8unHeQlQCc'
    'Na3chj/AoGj/ZGyaWFpmwErEizhZPcyweH5xcdwJK4Zj7+300S8wz3bnyPBkxPVRzf2mNV5oTMcR/SpZIj519f1vyieaxxuG'
    'CVDMpGB9gfUKO3+KgGIv9vH8vqPFda5hnTtncMZVKTLBMn9mkSrouzxp7DpZELDztfPzFHbYtWO77moKt/mF77F7SsT432L3'
    'FGvbjH1YiHhaXsdHbHzuuC88YcFpEbBTw72hz3r+NOU1eB8DAD6+HVvPm6lgwTNx7VmvvOsN2Nv84kvnfZP04tGb04b1DT4V'
    'HQ3yf4DtXkCTj7D9iIlNLTAVlOmfXkza9Fte4uS8hMIT/uELVXVLbkb2rhDRLsDsUCwqorj6M0CmWUBd7Z0B/ihhQyN6wH05'
    'hzgiZ4+in5eDrwK48tYilodlMeaE9czOU+QSx3edU7Qc6bLI2aLzOiqxcQblkiUoYoPgN8kinDK1BAt5jBguMFfTAFgCIinE'
    'UXhBmHEkPqd2AXJfkERcLRZH2SpbyMLjc0whyzsldncso0ltDMFuJaeQ6hyOwBYutW2F2ZQkPEglxf3PUi4D2tP1yLQUULkk'
    'l/s4CE/NmOz3+0nuY6l/y2V2vH5yuGcDu6yaiVtE7ttdyh5GvTgvaJKc6YDdVuFcGxL6k5s8ClIpus6zGFu8RJsXEZWxWVhV'
    'US5B1SDJBqL19hXsSYCgJB5vT+/QfvLA+yglxodeF6TKzQPVrjrWn8E2EzGvxbMIzmZ1E1dQ1CVR4+77I6f3zaJcKVA2Yve9'
    'JTEnJbz6RmxLvINatGbs3oD1L7Ddc4xi7dG1SF1vsCKhNUSISAZdg/DA2BZJw72R5hrvLC2Ff4FtHLd7MW7nm0ftuu6dLGdM'
    '9N02Od8wxRdjY1qCY45nW1u33aUHlx7iAvtTB2dG25SafFz4Q3U+78UctjXV2Riz4I7S3sclOdAihEa8SXzYprgfOydT1zqo'
    'kND5hN0CL0iVNzAIBU1dU4mF0JAUgD9IJlX8q7AKxznMyQmjSsWMZ+cv/K9g5xTRWXEqE3ZRUR4wWzth+m9pE1d+IJuy/FY0'
    'wxdet0UVIRkTFpeyxCZD/iJxguKjKiz/iyqBMkwMrQ4s4RlZWbgqViJYJFyEXyf4/QwWH4cak/7ozkET9BKLt0KwWzXAgrGb'
    'OCxKgfLsltuKsiqXgQXqkN+rM84ukAzUNas1eXnUFHHWc21g/it7W4rCiLpWT1wLfTl4k+YTllxq2U2zYbw7+9XisBprWPEq'
    '743q8RS+/FPBJDJ77meZay6KSbGwXKutAR/gySZWl7nmPOqstMsVlsE8ou2FCe+umNkD1r3B3vJZNrL9Q9jPDRQdC+7Pn39a'
    '2Ddg//mnTSgAe1/Qy+e5RR7w94VBM7GPd8j5GevFi/QMBi9O2yw8uWbasY3jestunM/zSrzBzpyI0CRE3dVePdnRm5H4zb72'
    'tLaIcqmi76PklzlZp6dHl4JQRwrCeBwUc+CNr3vLwTig81aiD9lXkQWWSh/7cnVG4ikVbLn64Y3hMrcD29ogKrn0sX7wjUVG'
    'T0FHHPJQhAnD1hpDWoCtOQYjtDD34Qf2icJNtIsErCoEE+avuczHiyAENpSBvNczWtsKFo9QZbgy8iTWUj7DKGCI/VxWMXLx'
    'tArRIYl4y0pxHyj6EX+uWR1hJZTFcZ4qA3v2ppJwL0lW61lG7Bw7ewMWKiVSYtSFLMcRxpwfbMeE3a5lOQkXuxH8RJgb6H3j'
    'Ir5nMEcRDeQpdVLwd6uIXBwTRPX3lKS4llIURwQNVHMuShy07GWcyuooOCmVN+a6wuspsVIq3mkGvq0U2lSOnGM93wgH1Jdi'
    'e88lfNMnMWCVyhIb15XAKaJipMi5TFFFLIHTl4Yq2pzpfdvGeaJDJm14ZAy5johxICfJBLFzEQbIWChIvSWOc0S7/FGEN7B9'
    'Z8nF4+8RtqZcB//5EdM1vLvpzGGPgpP+6FzmDOvPToRMlsqw/6UZL7OTNhuvnmWpd9Yr12y9Sqa5BmnON0/hrkTgJXh/5eNs'
    'Mgn5N/5QdDq3+0Pbse0WNP+UdF06496JUc9yFtV9uJOgvK4UdHMnShyrhTMbsMM7huSlzpJc8QGPoxrL5GF0WBcJ4qNuMqk/'
    'JKJ8MCPsBsYpS1Mq1gES0pRQGIcMdYysSFySOKJycqT6anLuSmkCDZux+Oqg3KrGYtGPLCUIJg8+qZjArEs5q4WDCOzIFpff'
    'YTROojrBID0QFfYwNyyhFNtMmNKkZkZHVS/iLVANJLD9ZfGYhhj2b7yHOeWvLvlujLCFbpVgE0lNGrcAilYEgvBqTsgOPYp7'
    'ePz4xKaJfIqFRS4+hYjjYrISEpsPZ0Zymfz+vVJYGhvRTltLhGHxYbckW03dAYNiwpJEmtOHv0u5W/KUrmdYHijlLmE517qG'
    'dYWt4hkGdeS3tZ5HU1o+QKirVp3NmAnCXHUzVLAVZPV6mdjRkQxCt27PcaAeAfg5etg9o4O/NhzCIKqBHJxnu7wX1ZCqekTb'
    'dcV871GWw03Ad6hVfesbJsMcyFl1a4HnGtGp3OJ8pbhqnK3r3R4XhO/iykjicSSKILlmO0Yu6Nui4vz/Ro6QqMxGScq3ceL/'
    'Ley/ZOmc0P1k39D1B5vTva6v25dRQQXyg0Fcfd8Pt0i0NNaAQ+8z1ZwMaxWg4l9zOqzCxfiazC9lE8yGAYespKI2ZFguENv3'
    '6cqctKHDgMiWF6atgMQZAy78prWlMDs6kpvt+JmmWB3Pa70q4sIWB0CDVUqOn5+f8P+u12H1iFtXAMarxj8PAPYZsENcBGIv'
    'HKqCFYYLumgOXBAXkRJEPgPXynV6GBKAWPPiOA7g3svJuIHcAkoSEtBOPV4oR3oBhiEne4RbiWvYV1gM4AIy/jeFtfmB/6/x'
    'IjgB9Qf3/t+gG14AvQNgDNyh8omuDsQxIb6HSjHGxahzSxyKA5J812NA1CnFBO5Tt7khT+CZnSPQpUrk2M6gwuPwJuD2w4i9'
    'p74H1e0yjsmvjY+izJkL89PBFeyJNgopx3kLplmSlEDEp5LdAJTyLj2/LcepuHdW0IwuDuOdXd8V4M/P9/ut8O2iDFYAHl84'
    '7oAw5AWw6/7TZ9fuXARWc2zkFaNZws2cYd/jJwfGRasMGOiPfJK1yFeQTlq8Uugt0Wt57yCwbez5o4At/H5/5uTRquyvu0Pp'
    'W1LtCx6CTHxTtLVPx9Ol09HE+f97EUGLCWNz+vlZGvhLsnZK05xmfk82Hu/IiP8Px7eFLhWUibUpHwviVOhAgLCty2K4xA05'
    'T+bmQkJMiEHArQ/eUy3by1px1+L7oKuiDq0XXJYgXpj5XE7xkW5JclysxtJEtUkngcec/bMvYhgkuGZuJtuw+Jl9czmVHAiF'
    'YEzjx7CltpErJXa6N3RQlQO/hxb7ZMqAx2zOATpfPu5YRY8o6eYD29jNDpU1b1J0pMKbKyX0hi7T1k3uVM6aRVGgPH4ZYnsM'
    'ckJeh44NIVuWNb/2IzcicmiYiG4M2hyNIsvDkOKLWqnUKV9ZXOht072lKO8SnwOXpYaDVQ3ukZkFcm0qkg9mOfz69YuLSoC1'
    'kMh8CoNSfcNoZLgakHGyhlGdNrdzyRiK13NSvkJV2J3lVdpSKQFwrK3ccW10p9JeeE16dTdpGEY9qEaqDXxOUc6fIHcodZSX'
    'wFZbh6+nSabp4snrGHMs9w021uKDqPRFUIT41Gwbf/Cqf4+4upp9Ct7rQvO+9XqqYHszYUlX72dbodvRLCcF1xsvyJ25MrqW'
    'rRDzXklTxb6arc6t1KLUUR5Jo1+u8x315OK6i41OLN85ydJ9kjxL/aW7a2hapdt1C8/uhdtxf+jpdemBRGjz0+Mb2qU3WEvq'
    'RH5zNEhD3ocKLQS6PWuK2/QQfG69b352p55h/n5VOMUA87Qfy2uendHev0hzyXUc71/pPFVz/1uyuMU2rc2VpkRlHl5d2GTF'
    'id9MmhsfUBnCF/VFjS5S+Y7Ug+duVKT+DWlYHg53ty8offLwQSSY695clIpFUlajb3+JqD+KodivVtKNxS00f5oXCxy9V0ts'
    'ISwVnCuvYu3dlKAn77n20Fy335yl3NRdPVGKUOz5T1/ORMX2R7En0qkqHLqJQJ63HLnysiipOi/PXFY5yBpixmbrSUZWqWNa'
    '5B2TwCvbJVwUKkAlUk8bMcv0LGxj65xB8S2s8sHlGoHd4u7YFxVoQdMbNcdLpKkz/Y7muBHDrahlH30UuMhCSZUoNyHdgRSD'
    'r2yqG5UykcXsTJF4kTYVhubS1qnklLVzalm67/1vXCCwr4cpw/pDSS1HNU5SBkrqcEx2YjkkARn3CSn7PEsScObWToQ70kpP'
    'NksMR3oT6XewfGtwhH3n4luqgXzJRXxBilPY5ap3H6zPcgN2It2xmluc5Ha7lXHjI6aMM57QAuqfSkc5aYiEroYX4rRPd7pn'
    'dc59swDYS+eofW9mktjqaWczPbkTmjfhSLmrh/QmqImutYODpe/fJP/17PRB0ncyCJLiVZ17VfcbvgDYMfv9NWmPisDev4gT'
    'Y1KijG6p96TyWN8ITvB4dJOwRkmPk97pC2BFqDE+ED++Xl+zWTUEBWZ3nW+P48wiFFwhIreQ7q6su9Ssy1J7ttdiMGUXN6mG'
    '9bt9133ltFL+72n/ipT08O7vDv93lCTUWsVFn4+ZQoXsGzKT8k6knWobDZirYnn2q5ifk7eiqCdrzYvpvXH9KCJsEd/W9yAj'
    'imSNThhN1JJYFo9Dd6hpyTBDqkMFoDQ/LqKy76i+ziW1am58xvFLS/KjGRvvK5bzO7BkHDyuJiqQXg/LUSRtj4vN4bY5tS9z'
    'ZbBu2/BVi99kW6jEcdyCjG+ZH4r2Ua6mmN67621cOXilmq7iFLjb8jLPwKLcAlzMCQIlwH+pIhEKKowKAHv8CE2isV7AcZhO'
    'BTBkXoglUo0cNZiaYWF9hFSaedNp0+iBSB7EWgP1I9rSVYo4JUfVGzYK2VihCnQxQqgs9B3t87PqFZFnbQMZ5T9xqgzlLnOv'
    'WmgHlZefx0ctHiNs8TunNuIxxjrOhWpgp5LMTGSspaVk/whToTtgUQe1VqLKjOIesZaKWM9GHEcq3wiUV+6jZQBvcTsx1KJc'
    '3o4pBktpKjTITNC7A3voVvZhRbUzWdyn7t2an0BFMgw5pdF69LBLzVIMVNxYDRuHF6o9kTVKHdBlSqgaJJ9eRE+maXNrnKka'
    'yMQYA2kBQ3uWkH9lv9WLAdaPVs001W71bFZpjeYFYbhLVC/qKKnOUa2GdyqtursGHSlPs3JcH7bhUp2Y2LkQ2Ev/xb+Qyjes'
    'uuOuVD71c25UZbxYI54TrgoXxN7kgpi1YTBrz3b3yFJVUBh8bnx958zZ8FH/+zrHnHy88ysS5Y1+TzTa5jCdSGXexkoZUQXe'
    'hGZRYtffUGk60zrB5Mtv0joSFYm/1ZX/XE3QGjPXqupH9lcZapSG4dgBiqgCWt7Os0IHZtAR+C+VOrc4llG7i7W2lC5XTOYg'
    '8Ryv5WIRgUQ15VQgyELxxw/3N47nZxX8Me4wl1KOxYgMDm0fMT8uGcRP+ctb6mCErS7maSJ/B+SkBQYFPRBL54YIicMIrZgX'
    'SI3mRDmUoIuPQEoDsaMCYkECmVSRwuidUmZOBYWymJPrDm2pqJUuGsS3CNpO+UJ+pHYSCX06EEd6hpqzk0faTO17KvWUunJV'
    'PE1b6rqEGWE6nGbrTN2Ll5plBaLOSTL7fUeG1P1qwf0X6gBkxePvqDgk3TxLXx+7sMogbAKobj99LMoAegZLD0MD1UZ5hkAF'
    'IYsxxfJJPty48KiWRh8Fjo3riuL8EtG9gWqlngRJWt4bpbYDHi+FfQ4yW3fLiL6sFiapFyZobQNVThaFzFsV/Tj2kmpAQeKG'
    'bGaqjGzAPLdLokmodk11b4mfJ5LTAnHcvkCUGsjfdf0Cz+TIAarUknVvM+5+P38XHFHNjs5DCswl480tdSeZw+TNPsoh7u18'
    '9+2rQV8f1KWN3opx41SngYeNWRNG3PqJGnmc0dYVdV6qyAg5nx/U+vD9qdhLjJuejSS/w+v7TTXdKKAXGrZziPRxKI4BsX+R'
    'GZqhen5lR3EKsbYZy1kx1lgvv44szZaxq51fLs+nVcj6xW1inNp4R4a2XSY7v0qUKYwSrTLF8kvtGO5DlG2kqzQdkUYilSAG'
    'nB/FwGabqtbuyQVe8x5E9Q6+4PK8V42mh3GI503pBeA+xSj91D4gT6Wt7VWgu98dh9aYWmy6p8rYIFjVLgG1js04XLb089PU'
    '0wTrEnn/r3+Jxe7C4SfjV7eRHos/3DUVjPc+PHQdNDdzwIP6yd0K+E+7oa97ZsKr8P30L1w5kbMdx4tuBZClBmSNXs+AQ8Pr'
    'C6f9cXxjxnmslN8YIgBXQDXKt1zFIwUSjU3syAlJNDO6trhVJPg5oDlSm9ELiKBIGMXV3FwobjGeaOYUA+Kv+1rQrqVJJDfN'
    'lxtDpvpQLAUqqzGqJlYc5z5HmdC28bZKYR893r3bUxhN4YlOYflSDh7DClUVjZxk23hr3ql5u5udHalPk+XS+npioh8xCTMc'
    'ItAkYLshHkkbuAOrypxKiUAStA5kF9fPunKnq0AF6ckfbrKM7Qx0bPcmvIOrinFZA2ruADTU1N2L6pHVkaWHY9HLSiSF7JcU'
    'KOnIIJFnlnTLPM/Ha/N8FvOGaj/ozKZ4f6Huym/pcuhV6DY/luIrwf5WgYYVNS/mR39RrWCGvmdIs3aQCKni5bk7yUk1dPtv'
    'DLzAyPxAr+x51b3GqVDASLFTIy6p4HH60rSxFq4B19lvC6iKTRNk6UiyC8lVcIFUaEeSc9evSpkQDuFCmjwQ62Kn3TSJPm6q'
    '5G9S2vZ0hevEW7kXnWzxsP17eXip4UM9zrSyryWbfXvMh/s7GorAicv1pmpXCvVrj3V7lTciCcTuHY1ofq3hJz69Ec0BK+nl'
    'eRGq/T6Wpqm7Vdd/TUP1sJOYdqAj8vOGhlRdO9v261H9sPBXe0opwFV2V9uymXFURJUiQ1fm8Yyq6SGZojJaW3anE0V4Jq7b'
    'sByrWyUnAUzCLUQbt4UFSzeQmTaiSIWtorGYWENsCGjik5VQnrkhfZs4PQT4glHdfNqIYJIUKdPiANlUDuh8bXCurQTLozNV'
    'e3ug2XTwBYgh+N7fE7EZgAWfiR1D5j52JUvbRVO1ERsSvSqf7zdt6nk2LFdYzcwzGMsWY0nkG8iDNc6dLowF+dceUBmGWU9J'
    'FXOg86ZkIGz1/UFBDMj5VG8DToPlDFFV5ygGD0/Q9tUC1VK09IbFwKgXKQCEUeGT5aM7dNnZje0fmG/Q98OgE8ztRJezMQAt'
    'DJ8ET4koGXSOP34IkWr6gaYhhk8LpYVWY/xzNJ+FjyD8BfL+D7XaNsOAqxZXIq4hNU9HW4NzvG2Ri47LJoxUbw3ufkjlCiRc'
    'hmNgdBVxrg028ppJo/ZRF9o2mb9KVRRLlZZmnFTkXzzB856rU6jpzTDdYVpYKARsgv8MqR56w6gQCsqBPlmq7iJDsHwDzfZo'
    'oorF8kdF5d9QpYiyJokifgCpjlxjhbXoH1BE7imcTwXyjFJ5+KlxQN7mS+oVPwehdPhaIBFVDnwoqhIzizp8ITwvxyN3NVJs'
    '1KQ3+ZkoPiPHhkKJjDMPz5ffO9/pAiTm+a0QxZGNe+ZB1sjTURXVePt28NeoqdpbWMIUjYoTfBs1HneJ7bUUK4EU7UVqao6T'
    'v6KDxpKt18z4rG2frS+6vYcXvW1hnSvr/flm9U4xdzu+KI7sdFE++6LXmGpbVbaiuSccsiu+IHQqOsjee1i11EW95GltgkRw'
    'e8lPklqxY/Jn5oyB25skpsxdL53lngb3dBj+ukmPekz4o1KK822XGSBcOaOSkww/T31Z8HFxKiYV8LecyHi/mrHXVbIurlIt'
    '9SkLY0ZCEpqREII7plhb+Cb2LQ4sHbcogTO+dsLPPNzQ+XoWauqlIJtFNkreZcO2LpOW196ii2AppXShwZdwwkBiZRWknj9L'
    'Ep5XpNuJMGWewHed4uq9U60Z4HnAts+GlIo32NUpV7KjkzFlGMjnr2LAKbXBZ5T0DEcKDEDLiiaMpSYnehl59ejpJ0IKmYjB'
    'yRQDDsrJMdHbWKYzg60cooJQ5AI6Sdm2k6sQ4lrObPaO7sfdUcMeitq2ENRVGr1YmGHCES3OMkuSI+yJGxMlTg4ymn3HAeVB'
    'qi7FZJ+KS4hRy2IWRdTpWMquSNdUGNnrPEBnWzgO6WHeUadcfGuauA0Xh3mTxEfL87LbQqfrCbt3V/SuerzpTwrBSk2BvV1R'
    'uaNrKvaRGT93XWBkb2x4up8Lk7SsDPVHdq/aWfALygvj3qk8lRoq/gVhRul9OyGs5N/090BvTHM567Lgyl8WX0kDmlgZ7W/o'
    'zWf2VEr6PfXI+9TsXyehUgodWCLfGsCTrD1a0jHalyrRkhbj31/YzH+hzagY6Hm2f6WXUFGWzxvVhC6MxaSRxbTPOvW6tdSy'
    '48V7kmyCltpetRNvnF5FIeP31c4rFtcgVNkPrVddr6rXdpHoK0vG0gta728MykDNJXDOeeEl8baqsC6QlzyHD+x7qu9SrdO0'
    'banZqrKu6sbv3p+KxOTm7DIIG667ooFF160jfdFntJtqjSrkCxKLyUWqQEqHCWqpK9Fo2bUddZmT7LDZjll7ipx4rRJz1iBF'
    'PHhx3Kf+upqaeHDUciaufkRhHKqaDsSCb3kpSGnsDnxyVsR29p2mdSp9UOJNlN9Z2mlCB07Nodh5zeUSgXiKQSrTNDGxfKun'
    'yi38HJE4XHxxXE0fG6yoRoz+bBb0JMsjdfiTQzzYE1kPZPVKGMO+MDtWtaGgH/9QFi2TrumYMMz/RSqZ8ugPMQAkGs9bWLsS'
    'laFlTHyV2oWfRA0aG+g9T35+duw5yKJFYgq0fGNucfhOEvG6D+37PdKgsIgfRWtkntdXxn/kfSGfRbBIwrN+db8qEAUv7Ntn'
    'nGtwa2tAgVcVs3alFrXW6Dx6eTV994YYaLF2DL5l+zs156DqMX718LjbtatSbVDJhS/Fenluh/cvqbl81h7jOd8Ry1fv+Um7'
    '9l57SUyMv8RmGuvW9J6Ugv1Waeb5KvRjGE3ft0x7APdmmzA83oc3+LtWMtllG+vDuwt70xPw6pHJhe0syFur8shS+NXOqpq/'
    'URh4FShBiRyJUS97qKyZ6BwH4TB7UXT/+RgAEZk7Cs59BnQSrgkyl6WKCFFi0B3c4/2nfLcokYLNNwoM0KrEczYyJZwpgYZD'
    'MaGnCX1j3FEki+BcKTJW7i0aM0Ce6YvYgDhNmwoYitVDTIuF+HoFTMEKKrXOFVafOMssEYKmnawsJFD1+f1AJT6q1MAhXA5b'
    'x2CpvGVJuRNS0cH3aVdBJAyjUg7Bl5DbYlJLHFhTBFpo/votd66dys/RbMN1P9gl9nveH3kOARqLJ0ZZyf5UN1IB9j1VC8y+'
    'LXcq9Rf/qFTTynu49Disr9bOUhUAVSGymjKVhnyouufTtcn0dr1D5JZa1z0MqQrp1TMXUioZF+urSHe6H43gzgP2JW6v83QM'
    'SuRaZdfArKSwPJpKLQWosRCm1XElZn4lLoC9GBy5U9NeeXa7FMhDHElI59dB/55upphmEuXp576vVwxXFtE+s5eeVqjO1mtL'
    'eda4XzSzvc0AFMyzuxkjEJ9wumXoFczkDUgvYJKvf4dSRRGuuXhePOyKM6v2rinPvBKXIXP/MMyfOe2iSg18wN5V4cewfY+p'
    'qKutrsMCjUIlgNFeiQCgc3B12NlfGMPAKzlT0n/FBLQlvm6pf0IRp68qKwFqnFXpVVqlxCsJFm7TlOupOCoHGFqysZQfyaJT'
    'Njynj/gHlHW1sdhQhSh/wUwyAQf1wqy5GhBmIsOyOvJswqYjLte1emDGfHKZU7QfSUurFPGiIrqM0qWftNOXKorTwuoKURsJ'
    'PoJiMSBWZdbHxilNOJYoWHtMAV2WX79+RRTG64pvM231YCP79Qth3NGwrPKJ3loCoTUYyw5lb6IbMCU7orAE2XjD1Chhe6zm'
    '56tC9r8gDmusoLxkCwTULzI1+dpIlDEVUAMlmFSNLh6Fu70aZYdFjPAv6Qaw7wWMsyzYrNaJ0LArLsBMDf/24irT7IvY8K6z'
    'CPzJViBVhbKyRb4QfC6cqEX3s7JRXn6JvTaYvxrronv8Lf8Dv3NDD7MUKN8cWGUecFLIxpjWAC/TijP3zpWJC8eYey+M4QKQ'
    '5gloyVcz3wNTlK+5vxeMB65H3VZGjHXp2ub4UFrOqH7ht0+Qmw3N98uIfqG4fYXr3hQTIc4ALeBMLE14FQ286oICw7md5Qm4'
    'jhA9HZF1E1BWyybWZzwiv6gB825LUH2gNqTyjgCfc+hr2WrA5EJyMcsWKavCSO42CZQXwHUrSzNeAZNSvoiYUnsuWw24VZ6f'
    'diqJ5LNVH3TO32udzhlI5RhjXH/grZVZsl037sAxvn6huiQ+UJyA3BZo51B/7Bs/njmTGCj2oRegG2t8NXw1O2lRw0hlFHbl'
    '3kcuiTXyqBdzP3QYjxWoUnkmCvdBIwrnMHALMbfLFjg5yltHZyXcS9+nWHVpFzhNE3dE8mGVOgQO3EWMgabD6LhkOgJcL5Vh'
    'dg4bw5ZwPtmEsUHzINfm5s/+ZJxT/ZlRxb3e001LfbMWPgN+MlTq7jBOqriZGwMt85Yr2LaprIyrUGYMdXzgaiTiP6BoLxhQ'
    'o8MYhwvUiv0upYDG1SaYYNXJ58VcYpzf1eQJNliIBXT+EiTva818ktqvsPxaEWS2hAJkPTl1S0MhiqoADGeNjVvVOVUttXgZ'
    'oKaU9ymN+IwCpWdJQqeTBmr+FHZVpD177wvjXideK5W+DJcUiwgb4LTNLMV9ktbw9dyR2uuzKQc44rAW1V5B7clw+6WKVdKM'
    'utqspvOHOwB05PkMOsjwtozE9hx2grrnPYANzPeiwrbWm5LrssXUOOY8s4yjDTxafRxwMYdPTWrNncdB9RY2kgGBaZgDZQ8M'
    'Rh5U4SU11BpT+VL5aG6IZVVxnE2kmNiVXMobUc0Kk2nbWBtuFcOPwZBeBcJLpTaXxXajHrgOJZYC0cL+WLfK4415P/U56Jek'
    'BqqNEmqTpEoEv4BDDVLaBy+WRY5GBRrYXepebM4+Z0hAvNuTYwnpc+2vetmwq1qj9cbLYFC0J/+bGcXQOGhfnzb12fJ3y2U9'
    'RynIrPIvIKFZ46N2wUa3MdMSwK4X/zHRHRhlycsULDPqjMpkWIg2Qgq+iZEewqU9REmTfW5SXMZLZsI89WsuYkwQBxR9KfkX'
    '1/dBDEKX0CZbyxZ/R/dL+rYwKmvZ0UmQJGdKSd3Rpi5fP+0pWJOQu29tEmq1UHFebK21dSKPO//nj5ffNzGOORd+dy7/feWC'
    'NQu16NpAtF3S77yJINcCG5xXnjr4fV/E8fZ3vy/LBr29FljQ+F3xrqB/Jy8Vj+N9XPVFWljJ+FlHLDixxN/Ln8G/V/09nMB2'
    'Xrvyq+zgyNuYDSrmFH/viPNlv2MHI7fz73tyjWEbnsRVmaCTzj70uwc8uUR6GQesX+TQl9/D3/D7zr/jM+z5H8T2e2K+Pf/j'
    '/Htm++nLGyPXi7/6naZON7zzfCLBnn5P8QjU/wgXuldxCp6djf3e7yp8weuHVfjhnn7fcwlplz5izhcGsr7HCHBf8YNmsoXr'
    'tUCUBlILGYdLOht2tsKjCMt49BKZJzvUU51p8xiWYfLuDGeIGVsRGOpbE+XZVsZVLi7GYNuXuUJwcefreUSbDwdp1xGQG3Q7'
    'xkz8It7N2ShkyKWFrGMcv1WNkpvK26lezTfud5BvHwC1gr9U6DG2Y4i2iuUsvgoCABVpk7xAjCDXSjECtmMJCPEb6StJiHGO'
    'UJcSy1B4RTOEcEhBbH/+bLn9KSEW4Hl//vz5h0s9aAgjliUg/mAcrkjP6xkhNc04Jtt+OXo4Hn/+/IdjNGguUyyVoBAgJoOr'
    'h24gxuR8v5s28CUErEJ03H2P0igliCBFx8d93CCCuhQkM4UQ39SSEHCwCpp5kviJREPm9xYRm8p0NcR6esEKQKkKY3kNjCPa'
    'XaXHMiJAnvj3j9OMKSEW7rv58yMx6wViQQniJ/YqoYJpfeHVRXXyB8qH4CB5BNzGsblqkL7qbXL7v/e93rQOgi5FW68jnEK4'
    'mlcrRyhequfhVTeGcwRFQnhfR4AXSSFqWWYKgRYBX4kKpijxq34X5FC7QXCLjT9/rjttIOSff8gqcRGVRzOtBtx49nz5K2OA'
    'IC67nT/nAaam6VcZX00xIg0ZX08+mAup4U5guJEVMjFhWLaqeRRFgJyFJNY/glE9M5+kzmyx+A1G0OWEHIZh4WziPCwMQKRH'
    'JFUMhataot1A+kdtdBJiJ2PzJ2DzTMpnLadSYRWfRZ+dXVItw0nS8zbcFD/UuAHqWgf90HIEIbPBqGTGYMwpZghH0k1cFtIn'
    'zbLGkdYC2BCUE4paD50kQow4jNLyHvfq7CSX+oya5Eoa00LOIeGyPcVU4EnY3lVpqZ4UMrjqljHzMN81nfSa08cLfzY5mYsB'
    'G8SQ8sncDhXTVmJUIkWFKkGITsaQFvhXP6fvjUs/9bNdrk6CRI/XLE6iirnzjSozqDIan06KRdmj9qpOxusAR47DglKpZKFw'
    'cimUS7WVuvWkeirK/t3JNFsMzUudnbOTpI7uHOwZtBd9ck9hnvSvdDLpe6ICa41MtFtRO5W+s+cnXf2kqMjqpGiLcoVOny2m'
    'q2Jr1UnIWN7zk2rYLinTJ43Xz3N+stNqr+9cX1ByNGY8WeihFKt4UoDVraIWvO9lsL7E3Z6UW9S4+4tT8LZcn5yttMPuSx6L'
    'kUNwpj+xr9mC9swWhPwkFvZw9XBLa3dlyd/78jazaONyEbzSm0/3GTf/KwbJ+t9UYZLSetCeWxiltoTTVIbgmSIdwZ/PWazA'
    'MeRigVEm7HmKJ088kiI+INVAc1DqO0XG7xFyd3ymMKeITqycseVhowa6E41sfdtY/EgmWqwjrTgonOSIRjvJ/ghnvUGGjuEf'
    'IPxrLhjXjQvkUWpn5Ale/JWTsF2Kk6f72aiUjrTAwVE9pn1u4A9VJyEk3yP32KjkCxosF1JZFBekk6gQQnCe0msphJEuL8oc'
    'GVE9xyQ6SWlLvCF+MMjyXOm4iSGhEzPL2smxDGngVQato/TlpGoqPn8cGbtSltfsJNbpVtZdOblkyRRrNtulOLloE0Q6qRec'
    'T0KJbKisDQ2Udt2aKNLEUti/k5NSZ7sui7guS1WgSOjMG+LJFrNX0gayotg7h27okxhfeFbp7k9Kiuwu6qIyK/p0kv2w7hSy'
    '6ConfcrdFg3SlcNWT0obSi4JX1QIKa6ZnfSnk74MeOGT3fkkeskI5MqTjk+WFUu8Lgd4ylHgqjPVusqsb17oi+76pFdv0il7'
    'wjtkdLW0TNyqnKRy+JLysmhN1o7xlOSQ16ApK7RXc/+77v8DohHkaw=='
))

_META = [
    ('f042', 41, 56, 20, 55, 0),
    ('f043', 40, 58, 20, 57, 2296),
    ('f188', 36, 44, 18, 43, 4616),
    ('f189', 35, 42, 17, 41, 6200),
    ('f190', 41, 42, 20, 41, 7670),
    ('f191', 40, 42, 20, 41, 9392),
    ('f192', 49, 42, 24, 41, 11072),
    ('f193', 47, 43, 23, 42, 13130),
    ('f100', 44, 57, 22, 56, 15151),
    ('f101', 44, 57, 22, 56, 17659),
    ('f102', 44, 57, 22, 56, 20167),
    ('f103', 44, 54, 22, 53, 22675),
    ('f104', 39, 51, 19, 50, 25051),
    ('f105', 41, 51, 20, 50, 27040),
    ('f058', 56, 58, 28, 57, 29131),
    ('f233', 59, 55, 29, 54, 32379),
    ('f057', 54, 56, 27, 55, 35624),
    ('f152', 54, 41, 27, 40, 38648),
    ('f209', 32, 41, 16, 40, 40862),
    ('f231', 51, 47, 25, 46, 42174),
    ('f254', 54, 51, 27, 50, 44571),
    ('f060', 57, 50, 28, 49, 47325),
    ('f235', 61, 50, 30, 49, 50175),
    ('f236', 41, 48, 20, 47, 53225),
    ('f237', 38, 47, 19, 46, 55193),
    ('f240', 41, 41, 20, 40, 56979),
    ('f241', 38, 27, 19, 26, 58660),
    ('f242', 37, 19, 18, 18, 59686),
    ('f248', 24, 63, 12, 62, 60389),
    ('f249', 34, 61, 17, 60, 61901),
    ('f250', 29, 63, 14, 62, 63975),
    ('f251', 29, 62, 14, 61, 65802),
]

FRAMES = {f: (w, h, ax, ay, _BLOB[o:o + w * h]) for f, w, h, ax, ay, o in _META}

ANIMS = {'idle': ['f042', 'f043'], 'run': ['f188', 'f189', 'f190', 'f191', 'f192', 'f193'], 'jump': ['f100', 'f101', 'f102'], 'fall': ['f103', 'f104', 'f105'], 'shoot': ['f058', 'f233', 'f057'], 'shoot_run': ['f152', 'f209'], 'crouch': ['f231'], 'crouch_shoot': ['f254', 'f060', 'f235'], 'death': ['f236', 'f237', 'f240', 'f241', 'f242'], 'victory': ['f248', 'f249', 'f250', 'f251']}

ANIM_FPS = {'idle': 3.0, 'run': 12.0, 'jump': 8.0, 'fall': 8.0, 'shoot': 12.0, 'shoot_run': 10.0, 'crouch': 4.0, 'crouch_shoot': 12.0, 'death': 7.0, 'victory': 4.0}

del _META, _BLOB
