"""GENERATED by tools/build_run_frames.py - do not edit by hand.

Upright run / run-and-shoot frames for the palette-swapped sprites. Same format as
assets_data.FRAMES; ANIMS entries here replace the ones in assets_data.
"""
import base64 as _b64
import zlib as _zlib

_BLOB = _zlib.decompress(_b64.b64decode(
    'eNqtnGuCqzgOhWsL2kEBGwhkA0A2MLY30OANdPb/Z6Qj2UDCw9RMuqru7VuWH8LBn45Efn7yi9Lr5+TFv67ruuKvqjlpSdyk'
    '4lZ1I62bo4bUcJumadpWftY1Hfcmv5d29UmHhCExPbGoq6NmtQ5nr2p/XExOVtDpq20Op6evrntKu/qqXV233KypjqbXyNyb'
    'ruU/ntLrUbv6V9zLA1Y1f7ddfTIuN5HJyfeRm2mUi8rtntzq+WwPuxt6aQe3PHgdhxd3HF/SpY7c1AfbhYbx9XoNo1y1lptV'
    '+1eXxuE1jqM0rn8ruWb7l5de8uKW0mnNrmRDkn37OeqLO5R2Mkvpd+yJW80zfbQjbjjI77nHYZBJEMU50rYh9bKGl8xP20mz'
    'eeJ2Ma7fVDToiNJAOuWeZVB5RfnylJ086ktXwz1Ks4nb8OAxeq9d0mijopl8D4Psrlb7nJ2XliQXY0wNzTkdrjMaTjM346aO'
    'SCb2WvU4Plbt5tkHH0KYicwjr9TjMMuoXcfLjdNkC4riUm0HV/Mq5ij75hln+RWvBS/KrpGhZRJiLvumlT5wa5q5V0obS66I'
    'OWTigWPboR1+G/PfpBE3Sw7GnCItt7LV3uKhvXPc3+Qxp7i7t/qBF09eXyFO8WhPw+tBmwX27NFbSa8OaTtuf9TOye/Ro/OB'
    'gjvpz0uD1O5kYFmJtaOjkUmmHgKmJv3SUTvMT5o5p85xdDQ/9YpLDXc7TC7m3+JLnBhof1xsXPYhZiczOGzHL95C5u69gdUf'
    '3MOM3UnJnXtuQQ8UtZ3Dij4bUvYGtglZS/cxQ7lM8t9yl0gj0/4ilpvJbkOZnezS1U3HJrjdDoQrum1nvvbrfU1O262s0R8u'
    '97JmWUb43MTk/uPDe/OvFHA1/ftzMu83GtJ2E7zfH14gbvferJnEe5/tMs9s/iVc4E1u+fOnVxFCbY56RSQ+pYpsKBHOKVVt'
    '+lfO6fiPqr60kO4bHO2YWFNdGCQwEwhR7KrpcoBayRA/q6tVkK21UQyraypqj9mfwthqCXYRBHz4qLuakHEj/9HIyfhsTtfM'
    'x9+y2Lp+CoiduZX4QB3QWriO18AE03XHIxAo6yXXTbENhHeElnoaA3hqW3DHf4jTdv0qx/yA9gw+cBE2Rvfg5q8X7SHfAHgQ'
    'BhrhqUZO8cfjxRjVj/TdvfGLMhEvmHdE92gf3I24YntL5T4wIWCOYdZL/NrKcCN/fxyN1PM/LnCEVoZUyiOj3xzOMoD1nwwG'
    'DDgC/MTC2S2KErO8rP8EV4IcBpbCcHzTDbh/tg+Yjb38WsdPUxsyXc7joDdg/3iYAZMSDeqeYbCWajsrZ+mtmNmL+OtHWAe3'
    'oAE/BuM5GUUJiI0c7tRthxFoMgM9TYZeHcDTmREwgCLxerRtKwYKgm45ownQO0Z7Byl4Os8/bQkTSFQpQi1kWkPU7RoTWmbu'
    'IoHHSTy3nKDcfopP7PBlvusjM8IVyxCCfRHw2h7gHM0ZV9RGpsGt2y7GA7CLmSSdAMec0f0wCpqnOa2Pzx83YWnxaICf5F8x'
    'kPNKphbjdHo+yNp1KxjTBTokv81CdOvIZSHn6PJs47ADDsMQwV+ePyTbRA5nnZO/tKDZrqHypnfXQ8Q5JHYO1wPoEE6hHO99'
    'uh5gjmgv/OSUhU695CWM83nn8iCP9vhiB0VhRjRrL1zePY4NXIB7JCByiqv8/+3hCIJbYqAhVHp3PB6Hc6KEdo4Sz8ha2OLI'
    'AODn194nuR5na3CfCH5BTaS3rN0g4CzCuWMQEMT4cvQDaJO/YyEs7W/B5a3+P+LaG8x6i3gJUNlQUz4UCdMo+zVUOC+Ig+DR'
    '5oorF7oEiSqgVVUJITM5MR23WQ68np7ph6p3iCR5vSSqF3BvGEq7Ai8QVg8LhAjH7/Etj+M/GU080V3rufCv4qkgoaymOdV2'
    'GYnAzOJsIPBT0f9DR13pK6p6mf5pkIqARLy/PswZjSnLfUpRKjbLUOLpX/k/HrytV/Kt7Q5VEoV0Ktlsv79Vhb9UzVMV3BR4'
    '6O5QHDMW64eNJMykbkamYevvxCaP0g9j29lOEHGaf+rm00FTpMM29BqzOAchubFgqRb+ritrbH9TYZ1GE/SGvn/MbduhKW84'
    '/tb4oMmRlO10UnKF0dBPDHotAjldRWW4r2NUyWf9aHAMmB77SX7VdBYBsgVDWoewsKF8bXobaTSQZWqv+JhsRZycGZ5ifLbT'
    '9pZOyq5j8t44gveAsBNjGpt080Qfki9oVA2hHprKxLgVhU7jF3gxzZK4TGc49I5jiKCamEs64PTBXoJow9jDaBhMEIOGQoIt'
    'JEv6UgSJpp5tBhzf3DsluMXJKdNr54/1JIXFJY0uCWEBkogIxZ14kHaOMu9s6V5Z3PoQgHk8wvx1SJAA2qK1ycHjFMWCMgn3'
    '5WhPdSMdRICB7ZyNG1Rc+z68AKgmEIIis76Wh/o+wKAXKiNNk3MmPjufA4Rdsc+bisVbZkqA5XziUaIz1Jh4pzn1vA4MHj88'
    'c2VbTvIOWkbg72mKJ7dFgoGsP+SooiSfZpGkMwe7W4xzsfx9I+wC2YChVK3K+yBh7bvEKCT5G3vx/S4yItujSDSU2fxkj0Mw'
    'LLMxJTG/CqlkbVHockrNie6gIr3pvgx5C+PuiZVikI6c4qU3dUoX12XcB4VQT9vmKDO7Bz2rZG4JWelpn47863Hot87DgGSv'
    '4ZISuvGPCDWvzAKIyEdbd5yC/cxR84wg/gkjlQyi1NCqRNperB6is4FGW/0C4c8vpih3bKLAxVPqOnHdqQXYRRhF2E7WwpR0'
    'di0JTCVE9WjrxHfPtjrO5tOYsp/DIPjUNty+6Tis5fXtjWNSo1FYxTECEu113Q+i6u6NQ4OKe5rSHkbJ8uOCji96MWJWtLOM'
    'lQlDzgO1EJVpiWPzOQwkveG1SJomI6IbaITVtIUiSYCDpl9jNoE0aTlZ/tdpjpZcXbLKCSZXowxY1SBIFQBupCobmbcSsqsA'
    'rEKwkdsYcAi3cqpK1pZwPKzRLuu0Q8oUyxkwM/pGSXlrHljxSqgQr36hSZU20bnofiuTYFk9B61k8GYzMK9K5jjOQqqYlCX1'
    'yQBppSaqiyV3rbURYqPpeOVCaE+WKg3JRNYwW/FIJ/NJvGsYLXy5tLeT9RUtQ878+KVyKj8SbebmgwiKLSz2ZEgBuWViljGd'
    'Jfcui98nGhEeg4o6CbSAdsLB06EOlJezzu6yo47FTj3t7Qr5JF5izpeEwBMSGVIoOFAhVDhNEtOlqsKd2sywFgVguoIxczNw'
    'WxZzNjFNqSrmiIlT/g0nqR5gb0KwxNknSi+piJ6uPGERYjwdm0zzrJMCuHsjqzCfmCAf61Itg05L1vLPEVMRUr3e5d0dUghw'
    'jGGUoesNuSpYyYE/Rjf6gDuL6sIZ7n3ZkPMXhEhfDEnv/7/Jz9e9oDzbTLdJT/U3ycZdFPrtC11VZVntO3nwlFat61KFsKkS'
    'X+G7ouIpNnWMqUSxbJYmXjWxLiRGm+JvlSr+oL7UpXM0DnyWQV12CESnpm4VBosdIpeMQRB805R7RBAN8+sg5lHxaFAB5ZCT'
    '61Y4y0qz4p2urXiS1W8qVuxKiNogq4fyWLW4Zl2h1diryKdyZekmEfRFgv1l753qt6S0Y+xBWL0YsxOHpvmti8xW5YeSk7fy'
    'SL09HL3TtcrAqhtNyUx1dVFO+KPaTsuIK01KBzCKlommuM3hrvyYqFAT36OoK6L2ReDapC9a8aeicaolMF4dNOk9QZcUKIz4'
    'i2ZkUwYsSc0vRUmjSc0mw0q/U56XLBFGSuGJQPnbOkZuLmd9RRZlgiUEGoQaQiP9hLsi7qJek5LohD/n+HjMXfuYUdBommti'
    '6qGfuyUXrlyZMumCmI85QXYKYoSWBXOtDDiVAsQuA6q4dkqpbJRmiMjdM2uL7/GmkzQzxpAM+WIKLxkgkBjIUAPqX1GKqktS'
    'X2Qj7gK4TklSHqzcLxfDagY/7ZalgnOmuFaiR2M09fmUS+2k7GBSfRk+ieuT0/tUTummVKr6ddB+F5C5jFMCONMcy24MCxqa'
    'uFx4y1vMhKNDsVkW6zyCjFKxBgQesvZdZkfBZ2k6yd8lZi5rl0nFLBE+l8pQQ8YiZ2ZxPovGZWaechnqTs76eDRjYBR8nhbE'
    'foYcTouwydxToAYboDuNHJb/o+s9YlO0/3UF08zNciooWEkvXVxr3SFfFa6nquvKbP2+PUP+jVl2nZaMhnOVl77KV80svOnE'
    'jvAe22x6ev/7779XNO8+62dNkKYrM/d9delKwtb9/12gfBUV/CFsOO7o5089aX5aWJPoviX0wKqYTbfxiNbMllXabqoDNChJ'
    'ad47wZMVlrZ40Km5YUtWK9FY/rm+a4u16vNVVXVvykh+PztgTF3uK7LqhrZpT59LOgx0pHIDNanP5x3bpOF3JueWu4p67IdW'
    'H+BqoSJ/2+4LaoxTotI/Eb48JTHf7sjB397jN40w5iBCusGTLPfLzxxpfj3jlAVYff5LcFHUZfp+yR7fKAs5xf9qcvUFcjhN'
    'qlKwMgI8Z1ctPqQh6cDyVa8qvSu7ZqkmXfMcqawi5/tNC+desD0S/nG8PtfG7/qzBddrupwEOHt7cElDm2GMAEwlfuPPKXMv'
    'oG/CkTm8EiNb+QgvIMYVwSdtGa/ZiFYeEeFbKmK+bKtVFFbVINqbRh/QsJV9o4EobM1oXOTy3uhfavs8z6F9osAGj0Ih+rBz'
    'OPTJNvM9RxL65JWohLK42bCeX9OcT14+QbWKWHX5MevnysozogBV3c3dtKJfBgYAPtl1lm40skpe0mfU8C/TTOt6BKfGqEvu'
    '7TEzjUc4hJisDHlOMSVtmM+txXjUEw1i+5QoZE5+IQxLO5yzVBaoRjlZBLNa3s5Jl4ozF3Z0mKFEQ51c2H9Oz07VULWaAjUb'
    'Mi5G3gQjRwfmMrT9Le/iEgS1EmJTr73WHccTGXetAWOgJEizsUaTZeFAtOpvn6pVpvU+uDqyJaj3K49/Pmd5KXM6q17Bbou3'
    '8u2k1wm2keaZbvENioNhO/Hb8F4e3sqqpTo8zvHeuIlbpd5+uqnw4tkECTs8ZJV746KEyEIWX/pgFcjfgiI1xJNzRTUvpO+E'
    'df0ThbKKXTxj57DWlGgLZw9c7gSPSACtapvKqs19qo32prKF9KxBka0P68dH7ZHSsvDatkVxifVHbB5C8H8B/1RG/Tdju1f/'
    'KeJAHTrdqPjeGgf/tznbrT78OUr63wMsja3oj7aN1PveDJCSba51vR2daZyEcKVtb0VJJus3at0qQt4rX7eK5xYfKlE3Fd0a'
    'OT/yeDfQsiTGus74VmxpFeGNKajlZVjrnFKr5dddc89nSJph1RpIVPfiWsTCEm9x2CP19uUup1E/5gIXTEuRqdhaZGytjsKD'
    'js+l8rvIVuAYH2CRHq3cvdoHxUOahUDA2Kbk0w5jfjmSbGDkCBpNQj2lkAiBGtFWoN4GblqGM1oeA09HSoCMmF4aQ0lZ5Vqb'
    'arMF8akYo0YzCA4aS5Ja8JYL1SGraIoybUJKFeuv/JkVI1qOEvjWPmikH2PT8Fej8QJZfZN+AsPwUdVkiRw7ctv20eZoLEVx'
    'tSUrcnrEinssE9SPY34SK8VvmitZfe4Ev7L1aHVXlu4ac1nytISDmvFI+Q6XUzOvtIJU1bRELfphFpb4WMVxck5almt5HNQy'
    'X1ZTwVyXwzhkYPLHW+ApMD84q4YahyUk7CfvTH6ek3Hs1mGHxIHqGInmENPZ0nV1ml1D/Gxx4Lr4+aNEakj1W0OrDwxomk7r'
    'hWC8jXesBlnr3vnLyrkwVQl2o7qX7FLT9zvEr+uzSD/lg8M5GToPdqReZmtwpLgQEaGkuCRVdFlA6XNlUJ4B2/HQ0xSvCZzy'
    'M5c+5xdsQ5aEDVndXirtXSrFK0sNWWBG9oScvC/Ka8ft3eA8pZh6ijfq1U319vnzI+byO7lWZKVoGMFHcViZBgy67vNCqw/b'
    'x0M/TCUXXZXTLbXyoGV60mP1aEQRwj/EuO20GN4qq1xpnuz90Fe7iB43smyrKndM+31n5uvqJrzweR17H+ZRYG3lZf4qfbMz'
    'c0r/4IMvrPH/KszSuf/VGubvP1sXVIV95Wo2MFBa9/VfR9hoVw=='
))

_META = [
    ('r00', 40, 59, 20, 58, 0),
    ('r01', 49, 56, 24, 55, 2360),
    ('r02', 52, 49, 26, 48, 5104),
    ('r03', 51, 50, 25, 49, 7652),
    ('s00', 55, 58, 27, 57, 10202),
    ('s01', 60, 57, 30, 56, 13392),
    ('s02', 62, 51, 31, 50, 16812),
]

FRAMES = {f: (w, h, ax, ay, _BLOB[o:o + w * h]) for f, w, h, ax, ay, o in _META}

ANIMS = {'run': ['r00', 'r01', 'r02', 'r03'], 'shoot_run': ['s00', 's01', 's02']}

ANIM_FPS = {'run': 10.0, 'shoot_run': 10.0}

del _META, _BLOB
