"""Import the per-character sprite sheets into ``assets_chars.py``.

Dev-only script (Pillow).  Usage:

    python tools/import_char_sheets.py

Source: ``sheets/<key>.png`` from the Claude Design "Character Sheets" page.
Each sheet is 432x800, transparent, 1x resolution, facing right.  One row per
animation (same order and frame count as ``assets_data.ANIMS``), cells 72x80,
feet on pixel row 77 of the cell (2 px above the cell bottom), body centred on
cell column 36.

Output: ``assets_chars.py`` at the project root with
    CHAR_FRAMES[key][frame_id] = (w, h, anchor_x, anchor_y, rgba)
rgba = w*h*4 bytes, row major, alpha either 0 or 255 (the overlay window uses a
colour key, so soft edges would fringe).  Frame ids match ``assets_data`` so
ANIMS / ANIM_FPS stay shared.
"""
from __future__ import annotations

import base64
import os
import sys
import zlib

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

import assets_data  # noqa: E402

SHEET_DIR = os.path.join(ROOT, "sheets")
OUT = os.path.join(ROOT, "assets_chars.py")

CHARS = ["jaehwi", "hyunki", "dongil"]
ROW_ORDER = ["idle", "run", "jump", "fall", "shoot", "shoot_run", "crouch",
             "crouch_shoot", "death", "victory"]
CELL_W, CELL_H = 72, 80
FOOT_Y = 77          # feet row inside a cell
CENTRE_X = 36        # body centre column inside a cell
ALPHA_CUT = 128


def cut_frame(img: Image.Image, col: int, row: int):
    """Crop one cell to its opaque bbox -> (w, h, ax, ay, rgba bytes)."""
    cx0, cy0 = col * CELL_W, row * CELL_H
    cell = img.crop((cx0, cy0, cx0 + CELL_W, cy0 + CELL_H))
    px = cell.load()
    xs, ys = [], []
    for y in range(CELL_H):
        for x in range(CELL_W):
            if px[x, y][3] >= ALPHA_CUT:
                xs.append(x)
                ys.append(y)
    if not xs:
        raise ValueError(f"empty cell row={row} col={col}")
    x0, x1, y0, y1 = min(xs), max(xs) + 1, min(ys), max(ys) + 1
    w, h = x1 - x0, y1 - y0
    out = bytearray()
    for y in range(y0, y1):
        for x in range(x0, x1):
            r, g, b, a = px[x, y]
            out += bytes((r, g, b, 255)) if a >= ALPHA_CUT else b"\x00\x00\x00\x00"
    return w, h, CENTRE_X - x0, FOOT_Y - y0, bytes(out)


def import_sheet(key: str):
    img = Image.open(os.path.join(SHEET_DIR, f"{key}.png")).convert("RGBA")
    if img.size != (CELL_W * 6, CELL_H * len(ROW_ORDER)):
        raise ValueError(f"{key}.png: unexpected size {img.size}")
    meta, blob = [], bytearray()
    for row, anim in enumerate(ROW_ORDER):
        for col, fid in enumerate(assets_data.ANIMS[anim]):
            w, h, ax, ay, rgba = cut_frame(img, col, row)
            meta.append((fid, w, h, ax, ay, len(blob)))
            blob += rgba
    return meta, bytes(blob)


def b64_lines(data: bytes, width: int = 100) -> str:
    s = base64.b64encode(zlib.compress(data, 9)).decode("ascii")
    return "\n".join(f"    '{s[i:i + width]}'" for i in range(0, len(s), width))


def main():
    parts = ['"""GENERATED by tools/import_char_sheets.py - do not edit by hand.',
             "",
             "Per-character RGBA frames cut from sheets/<key>.png.",
             "CHAR_FRAMES[key][frame_id] = (w, h, anchor_x, anchor_y, rgba); rgba = w*h*4 bytes,",
             "row major, facing right. anchor = bottom-centre (feet). Frame ids match assets_data.",
             '"""',
             "import base64 as _b64",
             "import zlib as _zlib",
             "",
             "CHAR_FRAMES = {}",
             ""]
    for key in CHARS:
        meta, blob = import_sheet(key)
        parts.append(f"_BLOB = _zlib.decompress(_b64.b64decode(\n{b64_lines(blob)}\n))")
        parts.append("_META = [")
        parts.extend(f"    {m!r}," for m in meta)
        parts.append("]")
        parts.append(f"CHAR_FRAMES[{key!r}] = {{f: (w, h, ax, ay, _BLOB[o:o + w * h * 4]) "
                     f"for f, w, h, ax, ay, o in _META}}")
        parts.append("")
        sizes = " ".join(f"{m[0]}:{m[1]}x{m[2]}@{m[3]},{m[4]}" for m in meta[:3])
        print(f"{key}: {len(meta)} frames, {len(blob)} rgba bytes  ({sizes} ...)")
    parts.append("del _META, _BLOB")
    parts.append("")
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(parts))
    print(f"-> {OUT} ({os.path.getsize(OUT)} bytes)")


if __name__ == "__main__":
    sys.exit(main())
